name: Build and distribute

on:
  push:
    branches:
      - main

jobs:
  android:
    name: android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  windows:
    name: windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build windows
      - uses: actions/upload-artifact@v4
        with:
          name: release-windows
          path: build/windows/x64/runner/Release

  web:
    name: web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build web
      - uses: actions/upload-artifact@v4
        with:
          name: release-web
          path: build/web